roasts_list=[           "I’d prefer a battle of wits, but you appear unarmed.",
                        #"If you were a potato you'd be a stupid potato.",
                        "Once upon a time, Santa Clause was asked what he thought of your mom, your sister and your grandma, and thus his catchphrase was born.",
                        "I'd love to stay and chat but I'd rather have type-2 diabetes",
                        "If I wanted a bitch, I would have bought a dog.",
                        "It’s a shame you can’t Photoshop your personality.",
                        "Calm down. Take a deep breath and then hold it for about twenty minutes.",
                        " You should wear a condom on your head. If you’re going to be a dick, you might as well dress like one. ",
                        "Whoever told you to be yourself gave you really bad advice.",
                        "I’m jealous of people who don’t know you.",
                        "Can you die of constipation? I ask because I’m worried about how full of shit you are.",
                        "I’d explain it to you but I left my English-to-Dumbass Dictionary at home.",
                        "I would roast you, but my Dad says I'm not allowed to burn trash.",
                        #"You are so ugly you make onions cry.",
                        #"You are so ugly, the mirror looked away.",
                        "You're so stupid you tried to wake a sleeping bag",
                        "You're like dobby from harry potter, only people won't be sad when you die in the seventh book.",
                        "If I asked you about your cock it wouldn't be a very long conversation.",
                        "You have the kinds of looks that make people talk about your personality.",
                        "You look like the result of pressing random on the character creation menu." ,
                        "You look like the after picture of a meth ad.","Even the shower doesn't want to see you naked.",
                        "I bet you wear a nose ring because no one wants to put one on your finger.",
                        "The only way you will ever get laid is if you crawl up a chickens ass and wait.",
                        "It looks like your face caught fire and someone tried to put it out with a hammer.",
                        "Your family tree must be a cactus because everyone on it is a prick.",
                        "You are proof that evolution can go in reverse.",
                        "You are the reason people didnt believe in Charles Darwins, \"Survival of the Fittest\" ",
                        "When you were born, the doctor came out to the waiting room and said to your dad, \"I'm very sorry. We did everything we could. But he pulled through.\"",
                        "I'd say you're funny, but looks aren't everything.",
                        "When I see your face theres not a thing I would change... Except for the direction I am walking in.",
                        "You're the cum your mother should have swallowed.",
                        "I heard your mom got fired from her job at the sperm bank - the boss caught her drinking on the job.",
                        "Twinkle twinkle little star, I want to hit you with my car, Throw you off a cliff so high, I hope you break your neck and die.",
                        "Some babies were dropped on their heads but you were clearly thrown at a wall.",
                        "I guess those penis enlargement pills are working - you're twice the dick you were yesterday!" ,
                        "Twinkle Twinkle little slut, name a guy you haven't fucked, was he skinny, was he tall, Nevermind you did them all." ,
                        "I failed a spelling test because they asked me how to spell 'bitch' and I wrote down your name.", 
                        #"You're like a light switch, even a little kid can turn you on.", 
                        "I don't see any dicks in the general vicinity... So I'm wondering why you keep opening your fucking mouth." ,
                        "Twinkle twinkle little slut, You like dick inside your butt." ,
                        "The last time I saw a face like yours I fed it a banana.", 
                        "Roses are red, violets are blue. I have five fingers and the middle one is for you.", 
                        "I'd like to kick you in the teeth but why improve your looks?", 
                        "At least there's one good thing about your body. It isn't as ugly as your face.", 
                        "Your the reason the gene pool needs a lifeguard.", 
                        "Your not yourself today, I noticed the improvement immediately." ,
                        "Is your butt jealous of the amount of shit that just came out of your mouth?" ,
                        "You\'d be suicidal if you felt as bad as you look." ,
                        "Your lips keep moving but I don\'t speak stupid." ,
                        "Calling you an idiot would be an insult to all stupid people." ,
                        "Brains aren\'t everything, in fact in your case they are nothing." ,
                        "I know your not as stupid as you look, Nobody could be!" ,
                        "You\'re kind of like Rapunzel except instead of letting down your hair, you let down everyone in your life." ,
                        "You have more dick in your personality than you do in your pants.", 
                        "You\'re so fat you need cheat codes to play Wii Fit.", 
                        "When I'm near you, my middle finger gets a boner.", 
                        "If I were your mirror I would commit self ded.", 
                        "Your face could scare the shit out of a toilet." ,
                        "Your so stupid I don\'t have the time or the crayons to explain this to you." ,
                        "If your IQ was multipled by anything it would still be the same." ,
                        "At least Hitler killed himself.",  
                        "When you were born your mom threw you out the window and the window threw you back.", 
                        "You're about as useful as Anne Frank's drum set.", 
                        "If I wanted to kill myself I'd climb your ego and jump to your IQ." ,
                        "I would burn you but burning trash is bad for the environment.", 
                        "I haven\'t seen you run that fast since Twinkies went on sale!" ,
                        "You were so ugly that when you were born the doctor put tinted windows on your incubator." ,
                        "I heard you received a brain transplant but it rejected your body." ,
                        "Someone once said your as pretty as a picture... I agree I would love to hang you." ,
                        "Your like Mondays, everyone hates you." , 
                        "It\'s better to let someone think you are an idiot then to open your mouth and prove it." ,
                        "You prove that even god makes mistakes sometimes." ,
                        "You\'re so dumb that you got hit by a parked car.", 
                        "I bet your brain feels as good as new, seeing that you never use it." ,
                        "What\'s the difference between you and eggs? Eggs get laid and you don\'t." , 
                        "I don\'t exactly hate you, but if you were on fire and I had water, I\'d drink it." ,
                        "God made you as an example of what not to do.", 
                        "You're proof that God has a sense of humor." ,
                        "You\'re so fat you could sell shade.", 
                        "You\'ll never be the man your mother is." ,
                        "Which sexual position produces the ugliest children? Ask your mother.", 
                        "I thought of you today. It reminded me to take the garbage out.", 
                        "You\'re so ugly when you look in the mirror, your reflection looks away."  ,
                        "I can\'t help imagining how much awesomer the world would be if your dad had just pulled out." ,
                        "Good story, but in what chapter do you STFU?" ,
                        "I\'d tell you to go fuck yourself, but that would be cruel punishment." ,
                        "You have the perfect face for radio." ,
                        "You\'re so ugly you make blind kids cry.", 
                        "Don\'t you need a license to be that ugly?" ,
                        "One more wrinkle and you\'d pass for a prune.", 
                        "You\'re so dumb, your dog teaches you tricks.",    
                        "You conserve toilet paper by using both sides." ,
                        "You're so stupid, you'd trip over a cordless phone.", 
                        "You're so stupid, it takes you an hour to cook minute rice." ,
                        "Don't feel sad, don't feel blue, Frankenstein was ugly too." ,
                        "You shouldn't play hide and seek, no one would look for you." ,
                        "You're so ugly, when you threw a boomerang it didn't come back." ,
                        "You're so ugly, when you got robbed, the robbers made you wear their masks." ,
                        "You're not completely useless, you can always serve as a bad example.",
                        "You have two parts of brain, 'left' and 'right'. In the left side, there's nothing right. In the right side, there's nothing left.",
                        "Two wrongs don't make a right, take your parents as an example.",
                        "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
                        "I'd like to see things from your point of view but I can't seem to get my head that far up my ass."]
                    
damage_attacks=["{} bitch slapped {}","{} ran a truck over {}","{} made a meme about {}","{} ate {}","{} used Thunderbolt {}","{} flex sealed {}","{} body slammed {}","{} used the Infinity Gauntlet on {}","{} bonked {}","{} threw a chair at {}","{} whacked {}",
                "{} used fake news on {}","{} used Avada Kedavara against {}","{} sang {}","{} jumped on {}","{} told John Wick that {} killed his dog","{} Force choked {}","{} pulled a Darth Vader on {}","{} used fake news on {}","{} bombed {}","{} puked on {}","{} threw a train on {}",
                "{} chop-chopped {}","{} used Thor's Hammer on {}","{} used Zeus's Thunderbolt on {}","{} performed a Windows update on {}","{} used a Plasma-Gun on {}","{} told The Mandalorian that {} took Baby Yoda","{} threw cupcakes at {}","{} nuked {}",
                "{} forced {} to play minesweeper for 18 straight hours","{} trolled {}","{} T-Posed in front of {}"]


